version: '3.3'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env.docker
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/api
      - /api/node_modules
    ports:
    - ${PORT}:${PORT}
    command: npm run start:prod
    env_file:
      - .env.docker
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: